# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 45e11891648aca854a85d46e36c705e52c39e37e6bd4eddd3f8f64fe572c008ac1712cb8c3e1a1daeedb599f3118099b9dc1a983168377b8e58ce1b92461bd7a

test:
  secret_key_base: cf54074cfe7ec4f1691f887aac3da0db6140c77c55c92d3a0c21abd03492f35f5290b9f7620043763aad0efc574176f72972543a6e846afe1f9fad633c636287

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
